var pokemonArray = [
    {name: "Bulbasaur", number: "1", rarity: "4", typeCombo: "Grass / Poison", fastMoves: "Tackle / Vine Whip"},
    {name: "Ivysaur", number: "2", rarity: "5", typeCombo: "Grass / Poison", fastMoves: "Razor Leaf / Vine Whip"},
    {name: "Venusaur", number: "3", rarity: "6", typeCombo: "Grass / Poison", fastMoves: "Razor Leaf / Vine Whip"},
    {name: "Charmander", number: "4", rarity: "4", typeCombo: "Fire", fastMoves: "Ember / Scratch"},
    {name: "Charmeleon", number: "5", rarity: "5", typeCombo: "Fire", fastMoves: "Ember / Fire Fang"},
    {name: "Charizard", number: "6", rarity: "6", typeCombo: "Fire / Flying", fastMoves: "Fire Spin / Air Slash"},
    {name: "Squirtle", number: "7", rarity: "4", typeCombo: "Water", fastMoves: "Tackle / Bubble"},
    {name: "Wartortle", number: "8", rarity: "5", typeCombo: "Water", fastMoves: "Bite / Water Gun"},
    {name: "Blastoise", number: "9", rarity: "6", typeCombo: "Water", fastMoves: "Bite / Water Gun"},
    {name: "Caterpie", number: "10", rarity: "1", typeCombo: "Bug", fastMoves: "Tackle / Bug Bite"},
    {name: "Metapod", number: "11", rarity: "3", typeCombo: "Bug", fastMoves: "Tackle / Bug Bite"},
    {name: "Butterfree", number: "12", rarity: "4", typeCombo: "Bug / Flying", fastMoves: "Struggle Bug / Confusion"},
    {name: "Weedle", number: "13", rarity: "1", typeCombo: "Bug / Poison", fastMoves: "Bug Bite / Poison Sting"},
    {name: "Kakuna", number: "14", rarity: "3", typeCombo: "Bug / Poison", fastMoves: "Bug Bite / Poison Sting"},
    {name: "Beedrill", number: "15", rarity: "4", typeCombo: "Bug / Poison", fastMoves: "Infestation / Poison Jab"},
    {name: "Pidgey", number: "16", rarity: "1", typeCombo: "Normal / Flying", fastMoves: "Tackle / Quick Attack"},
    {name: "Pidgeotto", number: "17", rarity: "3", typeCombo: "Normal / Flying", fastMoves: "Wing Attack / Steel Wing"},
    {name: "Pidgeot", number: "18", rarity: "4", typeCombo: "Normal / Flying", fastMoves: "Air Slash / Steel Wing"},
    {name: "Rattata", number: "19", rarity: "1", typeCombo: "Normal", fastMoves: "Tackle / Quick Attack"},
    {name: "Raticate", number: "20", rarity: "4", typeCombo: "Normal", fastMoves: "Bite / Quick Attack"},
];
